# Merge data for training

In [1]:
import numpy as np

# Load the data from the .npy file using np.load
data = np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/WithBaby_train/withbaby_train.npy')

# Print the size of the data (number of elements)
print(data.size)

# Or, print the shape of the data (dimensions) for multidimensional arrays
print(data.shape)
row,column = data.shape
print(row)

# Load the data from the .npy file using np.load
data1 = np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/WithoutBaby_train/withoutbaby_train.npy')

# Print the size of the data (number of elements)
print(data1.size)

# Or, print the shape of the data (dimensions) for multidimensional arrays
print(data1.shape)
row1,column1 = data1.shape
print(row1)

# Concatenate the arrays along axis 0 (vertically)
combined_data = np.concatenate((data, data1), axis=0)

# Print the shape of the combined data
print(combined_data.shape)

print(combined_data)

np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'train.npy', combined_data)


60000
(20000, 3)
20000
107034
(35678, 3)
35678
(55678, 3)
[[ 0.00000000e+00  9.56996284e+05  3.14159265e+00]
 [ 8.00000000e-01  3.14769763e+05 -1.45148141e-02]
 [ 1.60000000e+00  1.84662142e+05 -3.89914626e-02]
 ...
 [-1.34536689e+00  1.39716808e+05  1.26878180e+00]
 [-8.96911262e-01  2.53736935e+05 -1.83203999e+00]
 [-4.48455631e-01  1.24573277e+06  7.68107678e-02]]


# Create train label

In [2]:
# create a horizontal array with row and columns 
Label_person = np.ones((row))
Label_NoPerson = np.zeros((row1))
Label = np.concatenate((Label_person, Label_NoPerson), axis=0)

np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'train_label.npy', Label)

display=np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/train_label.npy')
print(display)

[1. 1. 1. ... 0. 0. 0.]
