# Merge data for testing

In [13]:
import numpy as np

In [14]:
# Load the data from the .npy file using np.load
#NOTE: uncomment here and in the daata save and label creation for the exact item in processing

data = np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/WithBaby_test/withbaby_test.npy')
#data = np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/Final/data/numpy_data/withbaby_Scarfblanket_test.npy')
#data = np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/Final/data/numpy_data/withbaby_all_test.npy')

# Print the size of the data (number of elements)
print(data.size)

# Or, print the shape of the data (dimensions) for multidimensional arrays
print(data.shape)
row,column = data.shape
print(row)

# Load the data from the .npy file using np.load
data1 = np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/WithoutBaby_test/withoutbaby_test.npy')

# Print the size of the data (number of elements)
print(data1.size)

# Or, print the shape of the data (dimensions) for multidimensional arrays
print(data1.shape)
row1,column1 = data1.shape
print(row1)

# Concatenate the arrays along axis 0 (vertically)
combined_data = np.concatenate((data, data1), axis=0)

# Print the shape of the combined data
print(combined_data.shape)

print(combined_data)

# data for baby present and absent normally 
np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'test_1.npy', combined_data)

#Data for baby present (with only suncreeen or scarf) and absent
#np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'test_2.npy', combined_data)

#data for baby present, with suncreen, with scarf and absent all together for testing
#np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'test_all.npy', combined_data)

122997
(40999, 3)
40999
60615
(20205, 3)
20205
(61204, 3)
[[ 0.00000000e+00  2.90456919e+06 -3.14159265e+00]
 [ 2.43908388e-02  1.41434112e+06  1.10751426e-01]
 [ 4.87816776e-02  2.08790877e+05 -1.43748806e+00]
 ...
 [-2.37564959e+00  2.85522536e+04  2.17655209e+00]
 [-1.58376639e+00  2.11311974e+05 -2.93380009e+00]
 [-7.91883197e-01  7.92780501e+05 -5.75361947e-02]]


# Create train label

In [15]:
# create a horizontal array with row and columns 
Label_person = np.ones((row))
print(len(Label_person))
Label_NoPerson = np.zeros((row1))
print(len(Label_NoPerson))
Label = np.concatenate((Label_person, Label_NoPerson), axis=0)

# data and label for baby present and absent normally 
np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'test_label_1.npy', Label)
display=np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/test_label_1.npy')

#Data and label for baby present (with only suncreeen or scarf) and absent
#np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'test_label_2.npy', Label)
#display=np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/test_label_2.npy')

#data and label for baby present, with suncreen, with scarf and absent all together for testing
#np.save('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/' + 'test_label_all.npy', Label)
#display=np.load('/Users/kushalprakash/Documents/Uni/23-24/AIS+ML/CombinedData/test_label_all.npy')
print(display)

40999
20205
[1. 1. 1. ... 0. 0. 0.]
